name: Github Pages

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/actions-setup@v4

      - name: Install node
        uses: actions/setup-node@v4
        with: 
          node-version: 20
          cache: 'pnpm'

      - run: pnpm install

      - run: pnpm run build

      - name: Deploy GH Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          publish_dir: ./dist
          github_token: ${{ secrets.GITHUB_TOKEN }}

